Repository Yamato-Security/suzaku, pull requests merged in 2025-04, with the labels that each got.

#25 fix: GitHub Actions release automation
  .github/workflows/release.yml
Labels: bug

#30 feat: update GitHub Actions for release to create Windows packages and fix the update-rules issue
  .github/workflows/release.yml
Labels: enhancement

#38 chg: default output profile yaml
  config/aws_ct_timeline_default_profile.txt
  config/default_profile.yaml
  src/aws_detect.rs
Labels: enhancement

#41 feat: add output-type option/ remove T and Z from timesamp/ update bytesize crate to2
  Cargo.lock
  Cargo.toml
  src/aws_detect.rs
  src/cmd.rs
  src/main.rs
  src/scan.rs
  src/util.rs
Labels: enhancement

#42 feat: Output standard out like Hayabusa
  src/aws_detect.rs
Labels: enhancement

#50 feat: add debug mode and saved file msgs
  Cargo.lock
  Cargo.toml
  src/aws_detect.rs
  src/cmd.rs
  src/main.rs
Labels: enhancement

#51 fix: no_color option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  contributors.txt
  src/aws_detect.rs
  src/color.rs
  src/main.rs
  src/scan.rs
  src/update.rs
Labels: bug

#56 fixed not valid a tag href
  README-Japanese.md
  README.md
Labels: documentation

#66 updated screenshot
  README-Japanese.md
  README.md
  screenshots/TerminalOutput.png
Labels: documentation

#69 feat: add aws-ct-summary
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config/abused_aws_api_calls.csv
  src/aws_detect.rs
  src/aws_summary.rs
  src/cmd.rs
  src/main.rs
  src/util.rs
Labels: enhancement

#73 fix: aws-ct-metrics csv header
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/aws_metrics.rs
Labels: bug

#74 feat: add GeoIP option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/cmd.rs
  src/cmd/aws_detect.rs
  src/cmd/aws_metrics.rs
  src/cmd/aws_summary.rs
  src/cmd/update.rs
  src/core.rs
  src/core/color.rs
  src/core/rules.rs
  src/core/scan.rs
  src/core/util.rs
  src/main.rs
  src/option.rs
  src/option/cli.rs
  src/option/geoip.rs
Labels: enhancement
